name: Compile WifiX Spacehuhn SDK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          # Pake URL sakti dari Spacehuhn biar packet injection gak mental
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Required Libraries
        run: |
          # Install SimpleCLI yang dibutuhin buat command line interface
          arduino-cli lib install "SimpleCLI"
          # Install ArduinoJson versi 5 (wajib buat project deauther lama)
          arduino-cli lib install "ArduinoJson"@5.13.5

      - name: Fix Structure and Compile
        run: |
          # 1. Bikin folder sesuai nama file .ino lu biar gak error
          mkdir -p WifiXv1.5
          cp -a . WifiXv1.5/ 2>/dev/null || true
          
          # 2. Bikin folder output
          mkdir -p build
          
          # 3. Compile pake FQBN khusus Deauther SDK (Flash 4MB, FS 2MB)
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          --output-dir ./build ./WifiXv1.5/WifiXv1.5.ino

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: WifiX-V1.5-Spacehuhn-Bin
          path: ./build/*.bin
