name: Compile Deauther Bin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Setup Stable Deauth Core (v2.6.3)
        run: |
          ./bin/arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          ./bin/arduino-cli core install esp8266:esp8266@2.6.3 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Fix Structure and Compile
        run: |
          # 1. Buat folder sesuai nama file .ino lu
          mkdir -p WifiXv1.5
          
          # 2. Copy SEMUA isi repo ke folder baru (biar oui.h dan LittleFS aman)
          cp -a . WifiXv1.5/ 2>/dev/null || true
          
          # 3. Buat folder output untuk hasil .bin
          mkdir -p build_output
          
          # 4. Compile dengan settingan Flash 4MB (1MB FS) biar gak mental
          ./bin/arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 \
            --build-property "build.flash_mode=dio" \
            --build-property "build.flash_size=4M1M" \
            --output-dir ./build_output WifiXv1.5/WifiXv1.5.ino

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WiFiX-V1.5-Final-Bin
          path: build_output/*.bin
